name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Укажите нужную версию Java

      - name: Build with Gradle
        run: ./gradlew build # Или mvn package, если используете Maven

      - name: Run tests
        run: ./gradlew test # Или mvn test, если используете Maven

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy to server
        run: ssh user@your-server "cd /path/to/your/app && git pull && ./deploy.sh"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
